// Données de démonstration insérées dans la base au premier démarrage (voir seed.ts).
import type { Product, Category, Shop, Order } from '../src/types';

const leatherHandbagImg = '/images/leather_handbag_1790991457488.jpg';
const africanWaxDressImg = '/images/african_wax_dress_1790991466302.jpg';
const ancHeadphonesImg = '/images/anc_headphones_1790991477811.jpg';
const rawHoneyImg = '/images/raw_savanna_honey_1790991488529.jpg';
const heroAfricanMarketImg = '/images/hero_african_market_1790991500113.jpg';
const artisanWoodworkerImg = '/images/artisan_woodworker_1790991510122.jpg';
const velvetArmchairImg = '/images/velvet_armchair_1790991523857.jpg';
const modernSmartphoneImg = '/images/modern_smartphone_1790991532691.jpg';
const smartwatchImg = '/images/smartwatch_fitpro.jpg';
const laptopImg = '/images/laptop_devices.jpg';

export {
  leatherHandbagImg,
  africanWaxDressImg,
  ancHeadphonesImg,
  rawHoneyImg,
  heroAfricanMarketImg,
  artisanWoodworkerImg,
  velvetArmchairImg,
  modernSmartphoneImg,
  smartwatchImg,
  laptopImg,
};

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'mode', name: 'Mode', icon: 'fa-shirt', description: 'Vêtements, accessoires', bgColor: 'bg-amber-50', textColor: 'text-amber-700' },
  { id: 'electronique', name: 'Électronique', icon: 'fa-laptop', description: 'Téléphones, ordinateurs', bgColor: 'bg-blue-50', textColor: 'text-blue-600' },
  { id: 'maison', name: 'Maison', icon: 'fa-couch', description: 'Meubles, décoration', bgColor: 'bg-orange-50', textColor: 'text-orange-600' },
  { id: 'beaute', name: 'Beauté', icon: 'fa-spa', description: 'Soins, cosmétiques', bgColor: 'bg-rose-50', textColor: 'text-rose-600' },
  { id: 'alimentation', name: 'Alimentation', icon: 'fa-apple-whole', description: 'Produits locaux', bgColor: 'bg-emerald-50', textColor: 'text-emerald-600' },
  { id: 'artisanat', name: 'Artisanat', icon: 'fa-paint-brush', description: 'Objets d’art, créations', bgColor: 'bg-yellow-50', textColor: 'text-yellow-700' },
  { id: 'agriculture', name: 'Agriculture', icon: 'fa-seedling', description: 'Produits agricoles', bgColor: 'bg-green-50', textColor: 'text-green-700' },
  { id: 'services', name: 'Services', icon: 'fa-handshake', description: 'Formation, réparation', bgColor: 'bg-indigo-50', textColor: 'text-indigo-600' },
];

export const INITIAL_SHOPS: Shop[] = [
  {
    id: 'afristyle',
    name: 'AfriStyle',
    location: 'Abidjan',
    articlesCount: 245,
    rating: 4.8,
    icon: 'fa-shirt',
    iconBg: 'bg-amber-100',
    iconColor: 'text-amber-800',
    description: 'Atelier de création sur-mesure et prêt-à-porter en pagne wax et tissé traditionnel Baoulé.',
    verified: true,
  },
  {
    id: 'tech-afrique',
    name: 'Tech Afrique',
    location: 'Marcory',
    articlesCount: 120,
    rating: 4.6,
    icon: 'fa-bolt',
    iconBg: 'bg-blue-100',
    iconColor: 'text-blue-700',
    description: 'Appareils électroniques certifiés, smartphones, ordinateurs et accessoires avec garantie 1 an.',
    verified: true,
  },
  {
    id: 'maison-deco',
    name: 'Maison Déco',
    location: 'Cocody',
    articlesCount: 98,
    rating: 4.7,
    icon: 'fa-house-chimney-window',
    iconBg: 'bg-orange-100',
    iconColor: 'text-orange-700',
    description: 'Mobilier design artisanal mêlant essences de bois tropical et velours contemporain.',
    verified: true,
  },
  {
    id: 'biofood-ci',
    name: 'BioFood CI',
    location: 'Yopougon',
    articlesCount: 175,
    rating: 4.9,
    icon: 'fa-leaf',
    iconBg: 'bg-emerald-100',
    iconColor: 'text-emerald-800',
    description: 'Produits agricoles biologiques de nos coopératives du Nord et de l’Ouest ivoirien.',
    verified: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'sac-cuir-anaya',
    title: 'Sac à main en cuir véritable',
    price: 25000,
    originalPrice: 30000,
    discountBadge: 'Promotion',
    category: 'mode',
    subcategory: 'Maroquinerie',
    brand: 'Collection Béthanie',
    rating: 4.8,
    reviewsCount: 124,
    location: 'Abidjan',
    stock: 18,
    isPromo: true,
    vendor: {
      id: 'boutique-anaya',
      name: 'Boutique Anaya',
      location: 'Abidjan, Cocody',
      verified: true,
      rating: 4.8,
      reviewsCount: 254,
      articlesCount: 86,
    },
    image: leatherHandbagImg,
    description: 'Élégant sac à main en cuir véritable, minutieusement façonné par des artisans maroquiniers ivoiriens. Cuir pleine fleur tanné naturellement, finitions en laiton brossé et doublure intérieure ornée de motifs géométriques africains. Parfait pour le quotidien et les grandes occasions.',
    characteristics: {
      'Matière principale': 'Cuir de vachette pleine fleur véritable',
      'Doublure': 'Coton imprimé motifs traditionnels',
      'Dimensions': '32 cm x 24 cm x 12 cm',
      'Fermeture': 'Zip robuste en métal doré et boucle avant',
      'Bandoulière': 'Amovible et réglable jusqu’à 120 cm',
      'Origine': 'Fait main en Côte d’Ivoire',
    },
    availableColors: [
      { name: 'Cognac artisanal', hex: '#8B4513' },
      { name: 'Havane brun', hex: '#5C2C16' },
      { name: 'Noir ébène', hex: '#1C1917' },
      { name: 'Terre cuite', hex: '#C25E37' },
    ],
    availableSizes: ['Taille unique'],
  },
  {
    id: 'robe-wax-afristyle',
    title: 'Robe africaine wax chic',
    price: 12000,
    originalPrice: 15000,
    discountBadge: 'Nouveau',
    category: 'mode',
    subcategory: 'Vêtements femme',
    brand: 'AfriStyle',
    rating: 4.7,
    reviewsCount: 58,
    location: 'Yopougon',
    stock: 24,
    isNew: true,
    vendor: {
      id: 'afristyle',
      name: 'AfriStyle',
      location: 'Yopougon, Abidjan',
      verified: true,
      rating: 4.8,
      reviewsCount: 180,
      articlesCount: 245,
    },
    image: africanWaxDressImg,
    description: 'Sublime robe évasée confectionnée dans un coton wax de première qualité aux motifs floraux et géométriques lumineux. Coupe cintrée mettant en valeur la silhouette avec fermeture éclair discrète au dos.',
    characteristics: {
      'Tissu': '100% Coton Wax hollandais garanti',
      'Longueur': 'Midi (au genou)',
      'Manches': 'Sans manches, col rond raffiné',
      'Entretien': 'Lavage doux 30°C ou à la main',
    },
    availableSizes: ['S', 'M', 'L', 'XL'],
    availableColors: [
      { name: 'Bleu & Or', hex: '#1E3A8A' },
      { name: 'Rouge & Jaune', hex: '#B91C1C' },
    ],
  },
  {
    id: 'casque-bluetooth-tech',
    title: 'Casque Bluetooth Pro Bass',
    price: 18000,
    originalPrice: 22000,
    discountBadge: 'Tendance',
    category: 'electronique',
    subcategory: 'Audio',
    brand: 'Nova Audio',
    rating: 4.6,
    reviewsCount: 81,
    location: 'Abidjan',
    stock: 35,
    isTrending: true,
    vendor: {
      id: 'tech-afrique',
      name: 'Tech Afrique',
      location: 'Marcory, Abidjan',
      verified: true,
      rating: 4.6,
      reviewsCount: 120,
      articlesCount: 120,
    },
    image: ancHeadphonesImg,
    description: 'Casque audio sans fil haute définition avec réduction active du bruit ambiant (ANC). Coussinets en mousse à mémoire de forme ultra confortables pour les trajets en transport et le travail.',
    characteristics: {
      'Autonomie': 'Jusqu’à 40 heures d’écoute continue',
      'Connectivité': 'Bluetooth 5.3 + Prise Jack 3.5mm incluse',
      'Microphone': 'Double micro avec réduction de bruit d’appel',
      'Recharge': 'USB-C charge rapide (10 min = 4h d’écoute)',
    },
    availableColors: [
      { name: 'Noir mat', hex: '#0F172A' },
      { name: 'Gris sidéral', hex: '#475569' },
    ],
  },
  {
    id: 'canape-velours-maison',
    title: 'Canapé velours salon 3 places',
    price: 250000,
    originalPrice: 280000,
    category: 'maison',
    subcategory: 'Mobilier',
    brand: 'Maison Déco',
    rating: 4.9,
    reviewsCount: 42,
    location: 'Cocody',
    stock: 5,
    vendor: {
      id: 'maison-deco',
      name: 'Maison Déco',
      location: 'Cocody Riviera, Abidjan',
      verified: true,
      rating: 4.7,
      reviewsCount: 98,
      articlesCount: 98,
    },
    image: velvetArmchairImg,
    description: 'Fauteuil et canapé contemporain revêtu d’un velours texturé haut de gamme jaune moutarde solaire. Structure robuste en teck ivoirien massif et pieds fuselés en laiton doré.',
    characteristics: {
      'Revêtement': 'Velours doux antitache haute résistance',
      'Structure': 'Bois de teck massif séché au four',
      'Suspension': 'Ressorts ensachés et mousse HR 35kg/m³',
      'Garantie': '3 ans constructeur',
    },
    availableColors: [
      { name: 'Jaune Moutarde Solaire', hex: '#D97706' },
      { name: 'Vert Émeraude Forêt', hex: '#065F46' },
      { name: 'Bleu Nuit Roi', hex: '#1E3A8A' },
    ],
  },
  {
    id: 'miel-pur-savane',
    title: 'Miel pur de savane (1L)',
    price: 5000,
    originalPrice: 6500,
    discountBadge: 'Bio',
    category: 'alimentation',
    subcategory: 'Produits du terroir',
    brand: 'BioFood CI',
    rating: 5.0,
    reviewsCount: 97,
    location: 'Korhogo',
    stock: 50,
    isBio: true,
    vendor: {
      id: 'biofood-ci',
      name: 'BioFood CI',
      location: 'Korhogo / Yopougon',
      verified: true,
      rating: 4.9,
      reviewsCount: 175,
      articlesCount: 175,
    },
    image: rawHoneyImg,
    description: 'Miel sauvage 100% pur et cru, récolté selon des méthodes traditionnelles respectueuses des abeilles dans les savanes préservées de la région du Poro (Korhogo). Non chauffé, non pasteurisé.',
    characteristics: {
      'Volume': '1 Litre (Poids net : 1.4 kg)',
      'Origine florale': 'Fleurs de karité, néré et savane boisée',
      'Certification': 'Origine Côte d’Ivoire Contrôlée & Bio',
      'Propriétés': 'Riche en antioxydants, antiseptique naturel',
    },
  },
  {
    id: 'smartphone-4g-128go',
    title: 'Smartphone 4G 128Go',
    price: 85000,
    originalPrice: 105000,
    discountBadge: '-20%',
    category: 'electronique',
    subcategory: 'Téléphonie',
    brand: 'Tech Afrique',
    rating: 4.7,
    reviewsCount: 112,
    location: 'Abidjan',
    stock: 19,
    isPromo: true,
    vendor: {
      id: 'tech-afrique',
      name: 'Tech Afrique',
      location: 'Marcory, Abidjan',
      verified: true,
      rating: 4.6,
      reviewsCount: 120,
      articlesCount: 120,
    },
    image: modernSmartphoneImg,
    description: 'Smartphone moderne écran immersif AMOLED 6.5 pouces, 128Go de stockage extensible, triple capteur photo 50MP et batterie monstre de 5000mAh tenant 2 jours complets.',
    characteristics: {
      'Écran': '6.5" Super AMOLED 90Hz Full HD+',
      'Mémoire': '6Go RAM + 128Go Stockage (microSD jusqu’à 1To)',
      'Appareil photo': 'Triple caméra 50MP + 8MP ultra-grand-angle',
      'Batterie': '5000 mAh avec charge rapide 25W',
      'SIM': 'Double nano-SIM 4G LTE compatible tous réseaux',
    },
    availableColors: [
      { name: 'Noir Minuit', hex: '#18181B' },
      { name: 'Bleu Océan', hex: '#0284C7' },
    ],
  },
  {
    id: 'smart-tv-43',
    title: 'Smart TV 43" 4K UHD HDR',
    price: 250000,
    originalPrice: 280000,
    discountBadge: 'Promotion',
    category: 'electronique',
    subcategory: 'Télévision',
    brand: 'Samsung',
    rating: 4.8,
    reviewsCount: 64,
    location: 'Abidjan',
    stock: 12,
    vendor: {
      id: 'tech-afrique',
      name: 'Tech Afrique',
      location: 'Marcory, Abidjan',
      verified: true,
      rating: 4.6,
      reviewsCount: 120,
      articlesCount: 120,
    },
    image: modernSmartphoneImg,
    description: 'Téléviseur connecté 4K Ultra Haute Définition avec processeur Crystal 4K, applications intégrées (YouTube, Netflix, Prime Video) et récepteur TNT intégré.',
    characteristics: {
      'Taille d’écran': '43 pouces (108 cm)',
      'Résolution': '3840 x 2160 pixels 4K UHD',
      'Système': 'Tizen OS avec Wi-Fi direct et Bluetooth',
    },
  },
  {
    id: 'tablette-samsung-tab',
    title: 'Tablette Samsung Galaxy Tab A9',
    price: 150000,
    originalPrice: 175000,
    category: 'electronique',
    subcategory: 'Tablettes',
    brand: 'Samsung',
    rating: 4.7,
    reviewsCount: 21,
    location: 'Marcory',
    stock: 8,
    vendor: {
      id: 'tech-afrique',
      name: 'Tech Afrique',
      location: 'Marcory, Abidjan',
      verified: true,
      rating: 4.6,
      reviewsCount: 120,
      articlesCount: 120,
    },
    image: laptopImg,
    description: 'Tablette compacte et fluide idéale pour les études, le travail nomade et le divertissement en famille avec haut-parleurs stéréo Dolby Atmos.',
    characteristics: {
      'Écran': '8.7 pouces WQXGA',
      'Stockage': '64Go extensible par carte microSD',
      'Connectivité': 'Wi-Fi + 4G LTE',
    },
  },
  {
    id: 'montre-connectee-fit',
    title: 'Montre connectée FitPro Active',
    price: 35000,
    originalPrice: 45000,
    category: 'electronique',
    subcategory: 'Montres & Objets',
    brand: 'Infinix',
    rating: 4.5,
    reviewsCount: 29,
    location: 'Plateau',
    stock: 25,
    vendor: {
      id: 'tech-afrique',
      name: 'Tech Afrique',
      location: 'Marcory, Abidjan',
      verified: true,
      rating: 4.6,
      reviewsCount: 120,
      articlesCount: 120,
    },
    image: smartwatchImg,
    description: 'Montre intelligente avec suivi cardiaque, podomètre, sommeil, notifications WhatsApp et appels Bluetooth au poignet.',
    characteristics: {
      'Étanchéité': 'IP68 résistante à l’eau et transpiration',
      'Autonomie': '7 jours en utilisation normale',
    },
  },
  {
    id: 'ecouteurs-sans-fil-tws',
    title: 'Écouteurs sans fil True Wireless Pods',
    price: 25000,
    originalPrice: 32000,
    category: 'electronique',
    subcategory: 'Audio',
    brand: 'HP',
    rating: 4.4,
    reviewsCount: 45,
    location: 'Treichville',
    stock: 40,
    vendor: {
      id: 'tech-afrique',
      name: 'Tech Afrique',
      location: 'Marcory, Abidjan',
      verified: true,
      rating: 4.6,
      reviewsCount: 120,
      articlesCount: 120,
    },
    image: ancHeadphonesImg,
    description: 'Écouteurs intra-auriculaires ergonomiques avec boîtier de charge compact, commandes tactiles et son stéréo immersif.',
    characteristics: {
      'Autonomie': '6h + 24h avec le boîtier de charge',
      'Microphone': 'Double micro ENC réduction de bruit',
    },
  },
  {
    id: 'iphone-13-128',
    title: 'Apple iPhone 13 128Go',
    price: 450000,
    originalPrice: 490000,
    category: 'electronique',
    subcategory: 'Téléphonie',
    brand: 'Apple',
    rating: 4.8,
    reviewsCount: 52,
    location: 'Abidjan',
    stock: 7,
    vendor: {
      id: 'tech-afrique',
      name: 'Tech Afrique',
      location: 'Marcory, Abidjan',
      verified: true,
      rating: 4.6,
      reviewsCount: 120,
      articlesCount: 120,
    },
    image: modernSmartphoneImg,
    description: 'iPhone 13 écran Super Retina XDR, puce A15 Bionic ultra-puissante, double capteur photo avancé avec mode Cinématique.',
    characteristics: {
      'Capacité': '128Go',
      'Réseau': '5G',
      'Garantie': '12 mois Apple Care',
    },
  },
  {
    id: 'samsung-s23-ultra',
    title: 'Samsung Galaxy S23 256Go',
    price: 520000,
    originalPrice: 560000,
    category: 'electronique',
    subcategory: 'Téléphonie',
    brand: 'Samsung',
    rating: 4.7,
    reviewsCount: 43,
    location: 'Cocody',
    stock: 6,
    vendor: {
      id: 'tech-afrique',
      name: 'Tech Afrique',
      location: 'Marcory, Abidjan',
      verified: true,
      rating: 4.6,
      reviewsCount: 120,
      articlesCount: 120,
    },
    image: modernSmartphoneImg,
    description: 'Le summum de la photographie mobile avec capteur 50MP Nighography et processeur Snapdragon 8 Gen 2.',
    characteristics: {
      'Capacité': '256Go',
      'RAM': '8Go',
      'Écran': 'Dynamic AMOLED 2X 120Hz',
    },
  },
  {
    id: 'hp-laptop-pavilion',
    title: 'HP Laptop Pavilion 15" Core i5',
    price: 280000,
    originalPrice: 320000,
    category: 'electronique',
    subcategory: 'Ordinateurs',
    brand: 'HP',
    rating: 4.6,
    reviewsCount: 37,
    location: 'Marcory',
    stock: 10,
    vendor: {
      id: 'tech-afrique',
      name: 'Tech Afrique',
      location: 'Marcory, Abidjan',
      verified: true,
      rating: 4.6,
      reviewsCount: 120,
      articlesCount: 120,
    },
    image: laptopImg,
    description: 'Ordinateur portable performant pour étudiants et professionnels. Intel Core i5 12e génération, 16Go RAM, SSD 512Go ultra-rapide.',
    characteristics: {
      'Processeur': 'Intel Core i5-1235U',
      'Mémoire': '16 Go DDR4',
      'Stockage': '512 Go SSD NVMe',
      'Écran': '15.6 pouces Full HD antireflet',
    },
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'BTH-123456',
    date: '02 oct. 2026',
    status: 'expédition',
    items: [
      {
        product: INITIAL_PRODUCTS[0], // Sac à main
        quantity: 1,
        selectedColor: 'Cognac artisanal',
      },
      {
        product: INITIAL_PRODUCTS[1], // Robe wax
        quantity: 1,
        selectedSize: 'M',
        selectedColor: 'Bleu & Or',
      },
      {
        product: INITIAL_PRODUCTS[2], // Casque bluetooth
        quantity: 1,
        selectedColor: 'Noir mat',
      },
    ],
    subtotal: 55000,
    deliveryFee: 2000,
    discount: 0,
    total: 57000,
    paymentMethod: 'Orange Money',
    phoneNumber: '+225 07 07 07 07',
    shippingAddress: 'Abidjan, Cocody Deux-Plateaux Vallons, Rue J75, Villa 12',
    deliveryDriver: {
      name: 'Mamadou K.',
      phone: '+225 05 44 33 22',
      vehicle: 'Moto Express Béthanie #14',
      eta: 'Aujourd’hui entre 15h30 et 17h00',
    },
    steps: [
      { step: 'Commande confirmée', date: '02 oct. 2026', time: '10:15', completed: true },
      { step: 'Préparation', date: '02 oct. 2026', time: '14:30', completed: true },
      { step: 'Expédition', date: '03 oct. 2026', time: '09:20', completed: true, current: true },
      { step: 'En livraison', date: '03 oct. 2026', time: 'En attente', completed: false },
      { step: 'Livrée', date: '', time: 'En attente', completed: false },
    ],
  },
  {
    id: 'BTH-120894',
    date: '24 sept. 2026',
    status: 'livrée',
    items: [
      {
        product: INITIAL_PRODUCTS[4], // Miel
        quantity: 2,
      },
    ],
    subtotal: 10000,
    deliveryFee: 1500,
    discount: 0,
    total: 11500,
    paymentMethod: 'Wave',
    phoneNumber: '+225 07 88 99 00',
    shippingAddress: 'Abidjan, Cocody Riviera 3',
    steps: [
      { step: 'Commande confirmée', date: '24 sept. 2026', completed: true },
      { step: 'Préparation', date: '24 sept. 2026', completed: true },
      { step: 'Expédition', date: '25 sept. 2026', completed: true },
      { step: 'En livraison', date: '25 sept. 2026', completed: true },
      { step: 'Livrée', date: '25 sept. 2026', completed: true },
    ],
  },
];

export const INITIAL_USER = {
  name: 'SHALOM PIERRE',
  email: 'pierre@gmail.com',
  phone: '+225 07 07 07 07',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  rating: 4.8,
  reviewsCount: 124,
  location: 'Abidjan, Côte d’Ivoire',
  stats: {
    commandes: 12,
    enCours: 3,
    favoris: 8,
    coupons: 5,
  },
  addresses: [
    { id: '1', title: 'Domicile', address: 'Cocody Deux-Plateaux Vallons, Rue J75, Villa 12, Abidjan', default: true },
    { id: '2', title: 'Bureau', address: 'Plateau, Immeuble CCIA, 4ème étage, Abidjan', default: false },
  ],
  paymentMethods: [
    { id: '1', type: 'Orange Money', number: '+225 07 07 07 07', default: true },
    { id: '2', type: 'Wave', number: '+225 07 07 07 07', default: false },
    { id: '3', type: 'Visa', number: '•••• •••• •••• 4289', default: false },
  ]
};
